// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddActionsWorkflow
{
    internal sealed partial class Vsix
    {
        public const string Id = "AddActionsWorkflow.727729af-a64d-474f-b03e-aaddf3b5dff6";
        public const string Name = "Add Actions Workflow";
        public const string Description = @"Adds a GitHub Actions workflow to the solution";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Tim Heuer";
        public const string Tags = "";
    }
}
