// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddActionsWorkflow
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AddActionsWorkflowString = "ff8107ff-c891-4674-878d-c283252ce550";
        public static Guid AddActionsWorkflow = new Guid(AddActionsWorkflowString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int AddWorkflowCommand = 0x0100;
        public const int LaunchRemoteUrlCommand = 0x0101;
    }
}